# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15e3efffd477905459fa2808295749ebfd8aece2f68b88ccc2f226e8e3267962088ef751ab3bd2d522980dd51ce6a6658b8a987e954605dc6307cdfa4ea1f09

test:
  secret_key_base: 5927d7db191d20cfb54dcffe1d0c09e5f020e03c5857bf38100f534b9e04706f7b4f34294e0ac7758859a1ade7d8f99d8779cb3cd0e28d393f3738ae5889921d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
